### ISSUE TITLE
Workflow Plugin clash

### ISSUE THREAD

**Issue by jbrew30** [trendyminds/isolate#14]
Hello, hope you're doing well! Thank you so much for working through my last issues. Since then, I've implemented a new [plug-in](https://plugins.craftcms.com/workflow) that works perfectly with yours but only on pre-existing entries. The way the plugin works is that it gives the user creating the new entry a button to submit it for approval. The funny thing is that it does send the entry to the approver but after you click the button it gives you this error (see below). I'm guessing this is happening because the table that tracks the specific entries doesn't know that the entry is associated with that user yet. Like I said on my first Issue request, I'm not against compensating you for the work you put into it. 
```
yii\web\ForbiddenHttpException: User is not permitted to perform this action in /Users/jbrewer/Documents/repos/goml-refresh/vendor/trendyminds/isolate/src/services/IsolateService.php:390
Stack trace:
#0 /Users/jbrewer/Documents/repos/goml-refresh/vendor/trendyminds/isolate/src/Isolate.php(75): trendyminds\isolate\services\IsolateService->verifyIsolatedUserAccess(347, 'entries/degreeP...')
#1 [internal function]: trendyminds\isolate\Isolate->trendyminds\isolate\{closure}(Object(craft\events\RegisterUrlRulesEvent))
#2 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\RegisterUrlRulesEvent))
#3 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\UrlMa...', 'registerCpUrlRu...', Object(craft\events\RegisterUrlRulesEvent))
#4 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/UrlManager.php(329): yii\base\Component->trigger('registerCpUrlRu...', Object(craft\events\RegisterUrlRulesEvent))
#5 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/UrlManager.php(98): craft\web\UrlManager->_getRules()
#6 [internal function]: craft\web\UrlManager->__construct(Array)
#7 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#8 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\web\\UrlMa...', Array, Array)
#9 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\UrlMa...', Array, Array)
#10 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#11 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('urlManager', true)
#12 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->get('urlManager', true)
#13 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Application.php(571): craft\web\Application->get('urlManager')
#14 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/Request.php(1032): yii\base\Application->getUrlManager()
#15 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/web/Application.php(82): craft\web\Request->resolve()
#16 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/jbrewer/Documents/repos/goml-refresh/web/index.php(21): yii\base\Application->run()
#19 /Users/jbrewer/.composer/vendor/laravel/valet/server.php(158): require('/Users/jbrewer/...')
#20 {main}
```

**Comment by aaronbushnell** [comment]
Hey @jbrew30! Can you send me a screenshot of your entire browser window when this error occurs? I seem to be able to submit these to the Workflow plugin without issues!

**Comment by jbrew30** [comment]
Steps to recreate the issue

Click "New entry" on an editor account. 

After filling in your necessary data, the editor should then click "**A**. Save draft and submit for review". This will alert the publisher via email and add it to their cue to approve it. The editor could simply click the "Create" button, which does not give you the error but also does not alert the publisher to the new entry.  Which then, in turn, creates a new issue of perhaps missing a newly-created entry for approval. 

<img width="1466" alt="Screen Shot 2020-05-28 at 4 36 42 PM" src="https://user-images.githubusercontent.com/22452733/83192899-2fac8d00-a104-11ea-883f-3801d1314a76.png">


**B**. Is a view of the error message that follows. 

<img width="1893" alt="Screen Shot 2020-05-28 at 4 28 54 PM" src="https://user-images.githubusercontent.com/22452733/83193026-64204900-a104-11ea-99db-b437bc5602ff.png">

**Comment by derezed** [comment]
Hey @jbrew30!

I was wondering if you could share some extra details for me! Mainly:

- The permissions for the user in question seeing this error
- Any user group permissions as well!

**Comment by jbrew30** [comment]
Oh, ok, cool. I was going to say the permissions are set up the exact way the [workflow plugin recommends](https://verbb.io/craft-plugins/workflow/docs/feature-tour/setup). That being one group of users are "editors," and the others are "publishers."
