### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by torgeirbeyer** [trendyminds/isolate#18]
Plugin does not work when you set the default language of control panel to Norwegian. It gives sql error when trying to save user permissions in the plugin, and a Twig Runtime Error when trying to edit the users via the Users tab in Craft control panel. It works fine when default language is set to English.

**Comment by nflorentin** [comment]
Same here, if user has the CP language in French. He can't access anymore the edit page of his preferences.

**Comment by aaronbushnell** [comment]
Should be fixed in #21 if you'd like to try again!
