### ISSUE TITLE
SQL Error when trying to save user permissions

### ISSUE THREAD

**Issue by mikephilippstock** [trendyminds/isolate#20]
URL: local
**Browser(s): chrome
**Other:**: Craft CMS 3.5.11.1, PHP 7.3.1, mySQL 5.7.25

Problem 1:
Trying to save a new user role (screenshot1) and getting an SQL error message (screenshot2)

Problem 2:
Trying to create a new user (screenshot3) and also getting a error message (screenshot4)

Thank you very much in advance!

screenshot1
![screenshot1](https://user-images.githubusercontent.com/23633005/94252891-d4a96c00-ff24-11ea-8447-d3add02d8027.png)

screenshot2
![screenshot2](https://user-images.githubusercontent.com/23633005/94252885-d410d580-ff24-11ea-82df-b812f7344bc8.png)

screenshot3
![screenshot3](https://user-images.githubusercontent.com/23633005/94252883-d3783f00-ff24-11ea-99c5-2880508d952a.png)

screenshot4
![screenshot4](https://user-images.githubusercontent.com/23633005/94252866-ceb38b00-ff24-11ea-9b12-4e2540e57249.png)

**Comment by mikephilippstock** [comment]
just found the solution by myself. Had to deactivate the plugin. Change the dashboard language of my admin craft user from "DE" to "EN". Activated the plugin again and now it all works fine.

Seems like dashboard language has to be set to "EN" for this to work. strange...

**Comment by aaronbushnell** [comment]
Hey @mikephilippstock this is due to only supporting English at this time. Language support is marked in #18 though! Closing to centralize this issue in one task.
