### ISSUE TITLE
Narrowing occurred during type inference

### ISSUE THREAD

**Issue by jbrew30** [trendyminds/isolate#24]
URL: Local and Production 
Device(s): iMac, Macbook pro, PC
Browser(s): Chrome, Firefox, Safari

Craft Pro 3.5.14
isolate 1.4.1
PHP 7.3
MySQL 5.5.5

**Steps to Recreate:**
- Step 1: Assign any entry to a user with the isolate plugin

yii\base\ErrorException: Undefined offset: 0 in /home/ubuntu/sites/goml-refresh/vendor/trendyminds/isolate/src/services/IsolateService.php:383
Stack trace:
#0 /home/ubuntu/sites/goml-refresh/vendor/craftcms/cms/src/web/ErrorHandler.php(76): craft\web\ErrorHandler->handleError()
#1 /home/ubuntu/sites/goml-refresh/vendor/trendyminds/isolate/src/services/IsolateService.php(383): craft\web\ErrorHandler->handleError()
#2 /home/ubuntu/sites/goml-refresh/vendor/trendyminds/isolate/src/Isolate.php(79): trendyminds\isolate\services\IsolateService->verifyIsolatedUserAccess()
#3 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/base/Event.php(312): trendyminds\isolate\Isolate->trendyminds\isolate\{closure:/home/ubuntu/sites/goml-refresh/vendor/trendyminds/isolate/src/Isolate.php:73-93}()
#4 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/base/Event.php(312): ::call_user_func:{/home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/base/Event.php:312}()
#5 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger()
#6 /home/ubuntu/sites/goml-refresh/vendor/craftcms/cms/src/web/UrlManager.php(334): craft\web\UrlManager->trigger()
#7 /home/ubuntu/sites/goml-refresh/vendor/craftcms/cms/src/web/UrlManager.php(97): craft\web\UrlManager->_getRules()
#8 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/di/Container.php(406): craft\web\UrlManager->__construct()
#9 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs()
#10 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build()
#11 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#12 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject()
#13 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/base/Module.php(742): craft\web\Application->get()
#14 /home/ubuntu/sites/goml-refresh/vendor/craftcms/cms/src/web/Application.php(324): craft\web\Application->get()
#15 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/base/Application.php(571): craft\web\Application->get()
#16 /home/ubuntu/sites/goml-refresh/vendor/craftcms/cms/src/web/Request.php(1249): craft\web\Application->getUrlManager()
#17 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/web/Application.php(82): craft\web\Request->resolve()
#18 /home/ubuntu/sites/goml-refresh/vendor/craftcms/cms/src/web/Application.php(259): craft\web\Application->handleRequest()
#19 /home/ubuntu/sites/goml-refresh/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#20 /home/ubuntu/sites/goml-refresh/web/index.php(21): craft\web\Application->run()
#21 {main}

![screenshot-goml-nitro-test-peachy-1603887925910](https://user-images.githubusercontent.com/22452733/97435848-68d96b00-18f7-11eb-8629-30268855c79d.png)

**Comment by aaronbushnell** [comment]
Hey @jbrew30 I'm unable to produce this error with the same version of Craft and Isolate. Any chance you could send me your database for inspection? If so you can DM me in the Craft CMS Discord if you're comfortable with sharing it that way.

**Comment by aaronbushnell** [comment]
@jbrew30 This should be fixed in `1.4.2`. Do you mind upgrading to confirm?

**Comment by jbrew30** [comment]
Thank you! That worked!!!
