### ISSUE TITLE
Error in user view

### ISSUE THREAD

**Issue by pette87** [trendyminds/isolate#3]
After install "isolate" I can't open users and groups in control panel.

Please see screenshot.
![isolateScreenshot](https://user-images.githubusercontent.com/11199719/57445796-6a225e00-7253-11e9-928d-df686a5c6a92.jpg)

Craft CMS 3.1.26

All works fine when the user use english language in backend, when we change to german the views are broken

**Comment by aaronbushnell** [comment]
Hey @pette87 can you send over a screenshot of your Sites setup? I'm trying to trigger this same error but not having any luck.

**Comment by pette87** [comment]
![isolateScreenshot](https://user-images.githubusercontent.com/11199719/57518164-baafbf00-7318-11e9-9bed-91135446844c.jpg)

here the screenshot

**Comment by aaronbushnell** [comment]
Thanks, @pette87! I'll investigate this further.

**Comment by Kreshimir** [comment]
Hey @aaronbushnell, isolate is really good plugin... but I have problem with pgslq database, I assume you made sql queries for msyql, do you have in mind to build it for pgsql?

**Comment by jripmeester** [comment]
Getting same issue as @pette87 here with Dutch language.

**Comment by watarutmnh** [comment]
Getting the same error as well in Japanese

PHP version | 7.3.14
MySQL | 5.7.29
Craft Pro | 3.4.23

**Comment by nflorentin** [comment]
Same error here with PHP 7.3.8, Craft CMS 3.4.24, PostgreSQL 11.3.

`Twig\Error\RuntimeError: Key "label" for array with keys "nested" does not exist. in /Users/nicolas/www/craftcms/linksium/vendor/craftcms/cms/src/templates/_includes/permissions.html:34
Stack trace:
#0 /Users/nicolas/www/craftcms/linksium/vendor/craftcms/cms/src/helpers/Template.php(96): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'label', Array, 'any', false, false)
#1 /Users/nicolas/www/craftcms/linksium/storage/runtime/compiled_templates/5b/5b4565b9b7032106fa1cf70fbacf25697f302dfe90453cadbf545fecbef15679.php(180): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'label', Array)
#2 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Extension/CoreExtension.php(1109): __TwigTemplate_8c56897310df28c7c81d5d2584aca415bbfe1129b3715fe257521bc87f87d564->macro_permissionList(Array, Array)
#3 /Users/nicolas/www/craftcms/linksium/storage/runtime/compiled_templates/5b/5b4565b9b7032106fa1cf70fbacf25697f302dfe90453cadbf545fecbef15679.php(79): twig_call_macro(Object(__TwigTemplate_8c56897310df28c7c81d5d2584aca415bbfe1129b3715fe257521bc87f87d564), 'macro_permissio...', Array, 66, Array, Object(Twig\Source))
#4 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(407): __TwigTemplate_8c56897310df28c7c81d5d2584aca415bbfe1129b3715fe257521bc87f87d564->doDisplay(Array, Array)
#5 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /Users/nicolas/www/craftcms/linksium/storage/runtime/compiled_templates/f9/f9dfcce9620ede0ff2b92f905bbbe4cc39ffec9d07b3cffe406237e4ee86c130.php(394): Twig\Template->display(Array)
#7 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(184): __TwigTemplate_89e32ef607fd16496c4975830cf446396c109b5198af0ad3b8ab6966d605a256->block_content(Array, Array)
#8 /Users/nicolas/www/craftcms/linksium/storage/runtime/compiled_templates/67/6700e17c17a98dcd5d5669fd1771c306e95ecdc702f59941541c7289730cb31c.php(411): Twig\Template->displayBlock('content', Array, Array)
#9 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(184): __TwigTemplate_5ca36394943a93f8f943fa73095945b9c1ce34a8f3d863a09fa82d70b03719f8->block_main(Array, Array)
#10 /Users/nicolas/www/craftcms/linksium/storage/runtime/compiled_templates/67/6700e17c17a98dcd5d5669fd1771c306e95ecdc702f59941541c7289730cb31c.php(266): Twig\Template->displayBlock('main', Array, Array)
#11 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(184): __TwigTemplate_5ca36394943a93f8f943fa73095945b9c1ce34a8f3d863a09fa82d70b03719f8->block_body(Array, Array)
#12 /Users/nicolas/www/craftcms/linksium/storage/runtime/compiled_templates/a5/a58cfb499b3649a8ecd086035d0ee3a43187332c136bd5c77c7de0585664e60d.php(75): Twig\Template->displayBlock('body', Array, Array)
#13 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(407): __TwigTemplate_e7afb8f2b1878e7b47ad8b7fe2bf3167aa2f2812b4ec266af9ad6390db24d057->doDisplay(Array, Array)
#14 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /Users/nicolas/www/craftcms/linksium/storage/runtime/compiled_templates/e3/e32a3d5cc61f6870d93c1cffc64b3e586c01210dcf1fb59eb2a278f3448d6ab7.php(56): Twig\Template->display(Array, Array)
#16 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(407): __TwigTemplate_51211dd6003425285b48766433c384261bb153330bf62d57f9298a9edf8b1fcb->doDisplay(Array, Array)
#17 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /Users/nicolas/www/craftcms/linksium/storage/runtime/compiled_templates/67/6700e17c17a98dcd5d5669fd1771c306e95ecdc702f59941541c7289730cb31c.php(138): Twig\Template->display(Array, Array)
#19 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(407): __TwigTemplate_5ca36394943a93f8f943fa73095945b9c1ce34a8f3d863a09fa82d70b03719f8->doDisplay(Array, Array)
#20 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /Users/nicolas/www/craftcms/linksium/storage/runtime/compiled_templates/f9/f9dfcce9620ede0ff2b92f905bbbe4cc39ffec9d07b3cffe406237e4ee86c130.php(117): Twig\Template->display(Array, Array)
#22 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(407): __TwigTemplate_89e32ef607fd16496c4975830cf446396c109b5198af0ad3b8ab6966d605a256->doDisplay(Array, Array)
#23 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#25 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#26 /Users/nicolas/www/craftcms/linksium/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#27 /Users/nicolas/www/craftcms/linksium/vendor/craftcms/cms/src/web/View.php(375): Twig\Environment->render('users/_edit', Array)
#28 /Users/nicolas/www/craftcms/linksium/vendor/craftcms/cms/src/web/View.php(436): craft\web\View->renderTemplate('users/_edit', Array)
#29 /Users/nicolas/www/craftcms/linksium/vendor/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate('users/_edit', Array, 'cp')
#30 /Users/nicolas/www/craftcms/linksium/vendor/craftcms/cms/src/controllers/UsersController.php(883): craft\web\Controller->renderTemplate('users/_edit', Array)
#31 [internal function]: craft\controllers\UsersController->actionEditUser('2', Object(craft\elements\User), NULL)
#32 /Users/nicolas/www/craftcms/linksium/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#33 /Users/nicolas/www/craftcms/linksium/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#34 /Users/nicolas/www/craftcms/linksium/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('edit-user', Array)
#35 /Users/nicolas/www/craftcms/linksium/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-user', Array)
#36 /Users/nicolas/www/craftcms/linksium/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('users/edit-user', Array)
#37 /Users/nicolas/www/craftcms/linksium/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('users/edit-user', Array)
#38 /Users/nicolas/www/craftcms/linksium/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#39 /Users/nicolas/www/craftcms/linksium/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#40 /Users/nicolas/www/craftcms/linksium/web/index.php(21): yii\base\Application->run()
#41 {main}`

**Comment by aaronbushnell** [comment]
Should be fixed in #21 if you'd like to try again!
