### ISSUE TITLE
List of entries includes 'trash' entries

### ISSUE THREAD

**Issue by marionnewlevant** [trendyminds/isolate#7]
Awesome plugin!

The list of entries to allow or deny access to includes trashed entries. My preference would be to exclude these from the list, or at least to indicate their status.

**Comment by aaronbushnell** [comment]
Thanks so much, @marionnewlevant! This is a great idea. I'll put it in my queue and see what we can do here. 

By the way—love hearing you on devMode.fm! 😃

**Comment by daltonrooney** [comment]
I think the list is displaying drafts and/or revisions as well. For example on the Homepage single, it's showing "Homepage" 16 times.

**Comment by jbrew30** [comment]
I have the same issue where I know I have 582 entries but it shows I have over a thousand. Makes the plugin unusable really. I love the concept and it's a much-needed plugin. Just Google "restrict access to entries in craft cms" and slowly figure out there is no good way to do this. I would be more than happy to pay for this plugin if it worked. Developers of this plugin TAKE MY MONEY.

**Comment by aaronbushnell** [comment]
Hey @jbrew30 @daltonrooney @marionnewlevant! I'm beginning a v1.2.0 version of this plugin and I believe the draft/revisions/trashed entries are now excluded when assigning users to entries.

Any of you mind being a guinea pig to test this out? 

**Warning**: This is not production ready so please test locally 😄

**Comment by jbrew30** [comment]
Worked for me! The duplicates are removed. I then picked three entries and added them to a dev account and all three were there. Nice and thank you! This might be a different topic/issue but if this plugin is active on a user, does the plugin remove the ability to create new entries for that user? When I click the "New Entry" button I get the error below. 

`yii\web\ForbiddenHttpException: User is not permitted to perform this action in /Users/jbrewer/Documents/repos/goml-refresh/vendor/trendyminds/isolate/src/services/IsolateService.php:390
Stack trace:
#0 /Users/jbrewer/Documents/repos/goml-refresh/vendor/trendyminds/isolate/src/Isolate.php(75): trendyminds\isolate\services\IsolateService->verifyIsolatedUserAccess(347, 'entries/degreeP...')
#1 [internal function]: trendyminds\isolate\Isolate->trendyminds\isolate\{closure}(Object(craft\events\RegisterUrlRulesEvent))
#2 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\RegisterUrlRulesEvent))
#3 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\UrlMa...', 'registerCpUrlRu...', Object(craft\events\RegisterUrlRulesEvent))
#4 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/UrlManager.php(329): yii\base\Component->trigger('registerCpUrlRu...', Object(craft\events\RegisterUrlRulesEvent))
#5 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/UrlManager.php(98): craft\web\UrlManager->_getRules()
#6 [internal function]: craft\web\UrlManager->__construct(Array)
#7 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#8 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\web\\UrlMa...', Array, Array)
#9 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\UrlMa...', Array, Array)
#10 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#11 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('urlManager', true)
#12 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->get('urlManager', true)
#13 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Application.php(571): craft\web\Application->get('urlManager')
#14 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/Request.php(1032): yii\base\Application->getUrlManager()
#15 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/web/Application.php(82): craft\web\Request->resolve()
#16 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/jbrewer/Documents/repos/goml-refresh/web/index.php(21): yii\base\Application->run()
#19 /Users/jbrewer/.composer/vendor/laravel/valet/server.php(158): require('/Users/jbrewer/...')
#20 {main}`

**Comment by aaronbushnell** [comment]
Hey @jbrew30 — just pushed an additional change! Mind seeing if that fixes the issue for you?

**Comment by jbrew30** [comment]
Yes! That work!!

**Comment by aaronbushnell** [comment]
Version 1.2.0 with Craft 3.2+ compatibility now available! https://plugins.craftcms.com/isolate#1.2.0
